spring:
  datasource:
    url: jdbc:h2:mem:inno-edu-db
  h2:
    console:
      enabled: true

flyway:
  cleanOnValidationError: true
  placeholders:
    map: lower

endpoints:
  sensitive: false

application:
  features:
    userBalanceValidation: true
  storage:
    mode: s3
    accessKey: AKIAJJ6UXMUOZ7LNG6BA
    secretKey: XHac+URvQSIs1ddfHlqmyw0xBszu3LSGnH7hC8CO
    bucket: inno-edu
  security:
    unsecured:
      - method: GET
        path: /**
      - method: POST
        path: /api/**
      - method: PUT
        path: /api/**
      - method: DELETE
        path: /api/**