flyway:
  cleanOnValidationError: true
  placeholders:
    map: unhex
endpoints:
  sensitive: false

application:
  security:
    unsecured:
      - method: POST
        path: /api/auth/login
      - method: POST
        path: /api/users
      - method: GET
        path: /swagger.yaml
      - method: GET
        path: /api/schools
      - method: GET
        path: /api/schools/{[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}}
      - method: GET
        path: /api/schools/{[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}}/mentors
      - method: GET
        path: /api/mentor-profiles/{[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}}
      - method: GET
        path: /api/availability/mentor/{[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}}