spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net/heroku_5b0c5e9a46aa7de?reconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: b8690d00c5b6ae
    password: bd0ed29a
  jpa:
    hibernate:
      ddl-auto: false
  jackson:
    serialization:
      write_dates_as_timestamps: false

flyway:
  schemas: heroku_5b0c5e9a46aa7de
  cleanOnValidationError: true
