spring:
  application:
    name: inno-edu-api
  profiles:
    active: dev
  jackson:
    serialization-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
      write_dates_as_timestamps: false
  jpa:
    hibernate:
      ddl-auto: false

