application:
  name: inno-edu-api

endpoints:
  sensitive: false

spring:
  datasource:
    url: jdbc:h2:mem:inno-edu-db
  jpa:
    hibernate:
      ddl-auto: false
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      write_dates_as_timestamps: false

flyway:
  schemas: inno-edu-db
