swagger: '2.0'
info:
  description: This the InnoEdu api.
  version: 1.0.0
  title: InnoEdu Api
  contact:
    email: apiteam@inno.edu
host: inno-edu-api.herokuapp.com
basePath: /api
tags:
  - name: users
    description: User management
  - name: schools
    description: School management
  - name: mentor-profiles
    description: Mentor profiles management
  - name: mentee-profiles
    description: Mentor profiles management
  - name: availability
    description: Mentor avaialbility management
  - name: appointments
    description: Appointments management
schemes:
  - https
  - http
paths:
  /users:
    get:
      tags:
        - users
      summary: Get all users
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmbeddedUserResourceList'
    post:
      tags:
        - users
      summary: Add a new user
      consumes:
        - application/json
      produces:
        - application/hal+json
      parameters:
        - in: body
          name: request
          description: Request object with the user information to be created
          required: true
          schema:
            $ref: '#/definitions/CreateUserRequest'
      responses:
        '201':
          description: New user successfully created
          schema:
            $ref: '#/definitions/User'
          headers:
            Location:
              type: string
              description: Link to the new resource created
        '400':
          description: Bad request, additional info provided in the response body
          schema:
            $ref: '#/definitions/VndErrors'
  /users/{id}:
    get:
      tags:
        - users
      summary: Get user by id
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/UserResource'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/VndErrors'
    put:
      tags:
        - users
      summary: Update user by id
      consumes:
        - application/json
      produces:
        - application/hal+json
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
        - in: body
          name: request
          description: Request object with the user information to be updated
          required: true
          schema:
            $ref: '#/definitions/UpdateUserRequest'
      responses:
        '201':
          description: User successfully updated
          schema:
            $ref: '#/definitions/User'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/VndErrors'
    delete:
      tags:
        - users
      summary: Delete user by id
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
      responses:
        '204':
          description: User successfully removed
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/VndErrors'
  /users/{id}/approve:
    put:
      tags:
        - users
      summary: Approve the current created mentor profile by user id
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
      responses:
        '204':
          description: User profile successfully approved
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/VndErrors'
        '400':
          description: User is not a mentor
          schema:
            $ref: '#/definitions/VndErrors'
  /users/{id}/reject:
    put:
      tags:
        - users
      summary: Reject the current created mentor profile by user id
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
      responses:
        '204':
          description: User profile successfully rejected
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/VndErrors'
        '400':
          description: User is not a mentor
          schema:
            $ref: '#/definitions/VndErrors'
  /users/{id}/profile:
    get:
      tags:
        - users
      summary: Get mentor or mentee profile by user by id
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/VndErrors'
        '400':
          description: Profile not found
          schema:
            $ref: '#/definitions/VndErrors'
  /schools:
    get:
      tags:
        - schools
      summary: Get all schools
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmbeddedSchoolResourceList'
    post:
      tags:
        - schools
      summary: Add a new school
      consumes:
        - application/json
      produces:
        - application/hal+json
      parameters:
        - in: body
          name: request
          description: Request object with the school information to be created
          required: true
          schema:
            $ref: '#/definitions/CreateSchoolRequest'
      responses:
        '201':
          description: New school successfully created
          schema:
            $ref: '#/definitions/School'
          headers:
            Location:
              type: string
              description: Link to the new resource created
  /schools/{id}:
    get:
      tags:
        - schools
      summary: Get school by id
      parameters:
        - in: path
          name: id
          description: School id
          required: true
          type: string
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/SchoolResource'
        '404':
          description: School not found
          schema:
            $ref: '#/definitions/VndErrors'
    put:
      tags:
        - schools
      summary: Update school by id
      consumes:
        - application/json
      produces:
        - application/hal+json
      parameters:
        - in: path
          name: id
          description: School id
          required: true
          type: string
        - in: body
          name: request
          description: Request object with the school information to be updated
          required: true
          schema:
            $ref: '#/definitions/UpdateSchoolRequest'
      responses:
        '201':
          description: School successfully updated
          schema:
            $ref: '#/definitions/School'
        '404':
          description: User not found
          schema:
            $ref: '#/definitions/VndErrors'
    delete:
      tags:
        - schools
      summary: Delete school by id
      parameters:
        - in: path
          name: id
          description: School id
          required: true
          type: string
      responses:
        '204':
          description: School successfully removed
        '404':
          description: School not found
          schema:
            $ref: '#/definitions/VndErrors'
  /schools/{id}/mentors:
    get:
      tags:
        - schools
      summary: Get school mentors
      parameters:
        - in: path
          name: id
          description: School id
          required: true
          type: string
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmbeddedMentorProfileUserResourceList'
        '404':
          description: School not found
          schema:
            $ref: '#/definitions/VndErrors'
  /mentor-profiles:
    get:
      tags:
        - mentor-profiles
      summary: Get all mentor profiles
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/EmbeddedMentorProfileResourceList'
    post:
      tags:
        - mentor-profiles
      summary: Add a new mentor profile
      consumes:
        - application/json
      produces:
        - application/hal+json
      parameters:
        - in: body
          name: request
          description: Request object with the mentor profile information to be created
          required: true
          schema:
            $ref: '#/definitions/CreateMentorProfileRequest'
      responses:
        '201':
          description: New mentor profile successfully created
          schema:
            $ref: '#/definitions/MentorProfile'
          headers:
            Location:
              type: string
              description: Link to the new resource created
        '400':
          description: Bad request, additional info provided in the response body
          schema:
            $ref: '#/definitions/VndErrors'
  /mentor-profiles/{id}:
    get:
      tags:
        - mentor-profiles
      summary: Get mentor profile by id
      parameters:
        - in: path
          name: id
          description: Mentor profile id
          required: true
          type: string
      produces:
        - application/hal+json
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/MentorProfileResource'
        '404':
          description: Profile not found
          schema:
            $ref: '#/definitions/VndErrors'
    put:
      tags:
        - mentor-profiles
      summary: Update mentor profile by id
      consumes:
        - application/json
      produces:
        - application/hal+json
      parameters:
        - in: path
          name: id
          description: Mentor profile id
          required: true
          type: string
        - in: body
          name: request
          description: Request object with the mentor profile information to be updated
          required: true
          schema:
            $ref: '#/definitions/UpdateMentorProfileRequest'
      responses:
        '201':
          description: Mentor profile successfully updated
          schema:
            $ref: '#/definitions/MentorProfile'
        '404':
          description: Profile not found
          schema:
            $ref: '#/definitions/VndErrors'
    delete:
      tags:
        - mentor-profiles
      summary: Delete mentor profile by id
      parameters:
        - in: path
          name: id
          description: Mentor profile id
          required: true
          type: string
      responses:
        '204':
          description: Mentor profile successfully removed
        '404':
          description: Mentor profile not found
          schema:
            $ref: '#/definitions/VndErrors'
  /mentor-profiles/{id}/approve:
    put:
      tags:
        - mentor-profiles
      summary: Approve a new mentor profile. All other profiles will be inactivated
      parameters:
        - in: path
          name: id
          description: User id
          required: true
          type: string
      responses:
        '204':
          description: Mentor profile successfully approved
        '404':
          description: Profile not found
          schema:
            $ref: '#/definitions/VndErrors'
  /mentor-profiles/{id}/reject:
    put:
      tags:
        - mentor-profiles
      summary: Reject the mentor profile
      parameters:
        - in: path
          name: id
          description: Mentor profile id
          required: true
          type: string
      responses:
        '204':
          description: Mentor profile profile successfully rejected
        '404':
          description: Profile not found
          schema:
            $ref: '#/definitions/VndErrors'
definitions:
  VndError:
    type: object
    properties:
      logref:
        type: string
      message:
        type: string
      links:
        type: array
        items:
          type: object
  VndErrors:
    type: array
    items:
      $ref: '#/definitions/VndError'
  CreateUserRequest:
    type: object
    properties:
      firstName:
        type: string
        maximum: 50
      lastName:
        type: string
        maximum: 50
      username:
        type: string
        maximum: 30
      email:
        type: string
        maximum: 255
      password:
        type: string
        maximum: 30
      confirmPassword:
        type: string
        maximum: 30
      isMentor:
        type: boolean
    required:
      - firstName
      - lastName
      - username
      - email
      - password
      - confirmPassword
      - isMentor
  UpdateUserRequest:
    type: object
    properties:
      firstName:
        type: string
        maximum: 50
      lastName:
        type: string
        maximum: 50
      email:
        type: string
        maximum: 255
      photoUrl:
        type: string
    required:
      - firstName
      - lastName
      - email
  User:
    type: object
    properties:
      id:
        type: string
      firstName:
        type: string
        maximum: 50
      lastName:
        type: string
        maximum: 50
      username:
        type: string
        maximum: 30
      email:
        type: string
        maximum: 255
      photoUrl:
        type: string
      isMentor:
        type: boolean
    required:
      - id
      - firstName
      - lastName
      - username
      - email
      - isMentor
  UserResource:
    allOf:
        - $ref: '#/definitions/User'
        - type: object
          properties:
            _links:
              type: object
  UserResourceList:
    type: object
    properties:
      userResourceList:
        type: array
        items:
          $ref: '#/definitions/UserResource'
  EmbeddedUserResourceList:
    type: object
    properties:
      _embedded:
        $ref: '#/definitions/UserResourceList'
      _links:
        type: object
  CreateSchoolRequest:
    type: object
    properties:
      name:
        type: string
        maximum: 255
      description:
        type: string
      photoUrl:
        type: string
        maximum: 255
    required:
      - name
      - description
      - photoUrl
  UpdateSchoolRequest:
    type: object
    properties:
      name:
        type: string
        maximum: 255
      description:
        type: string
      photoUrl:
        type: string
        maximum: 255
    required:
      - name
      - description
      - photoUrl
  School:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
        maximum: 255
      description:
        type: string
      photoUrl:
        type: string
        maximum: 255
    required:
      - id
      - name
      - description
      - photoUrl
  SchoolResource:
    allOf:
        - $ref: '#/definitions/School'
        - type: object
          properties:
            _links:
              type: object
  SchoolResourceList:
    type: object
    properties:
      schoolResourceList:
        type: array
        items:
          $ref: '#/definitions/SchoolResource'
  EmbeddedSchoolResourceList:
    type: object
    properties:
      _embedded:
        $ref: '#/definitions/SchoolResourceList'
      _links:
        type: object
  MentorProfileUser:
    type: object
    properties:
      id:
        type: string
      mentorId:
        type: string
      schoolId:
        type: string
      email:
        type: string
      description:
        type: string
      firstName:
        type: string
      secondName:
        type: string
  MentorProfileUserResource:
    allOf:
        - $ref: '#/definitions/MentorProfileUser'
        - type: object
          properties:
            _links:
              type: object
  MentorProfileUserResourceList:
    type: object
    properties:
      mentorProfileUserResourceList:
        type: array
        items:
          $ref: '#/definitions/MentorProfileUserResource'
  EmbeddedMentorProfileUserResourceList:
    type: object
    properties:
      _embedded:
        $ref: '#/definitions/MentorProfileUserResourceList'
      _links:
        type: object
  CreateMentorProfileRequest:
    type: object
    properties:
      mentorId:
        type: string
      schoolId:
        type: string
      email:
        type: string
        maximum: 255
      description:
        type: string
    required:
      - mentorId
      - schoolId
      - email
      - description
  UpdateMentorProfileRequest:
    type: object
    properties:
      description:
        type: string
    required:
      - description
  MentorProfile:
    type: object
    properties:
      id:
        type: string
      mentorId:
        type: string
      schoolId:
        type: string
      email:
        type: string
        maximum: 255
      description:
        type: string
      status:
        type: string
        enum: [CREATED, ACTIVE, INACTIVE, REJECTED]
    required:
      - id
      - mentorId
      - schoolId
      - email
      - description
      - status
  MentorProfileResource:
    allOf:
        - $ref: '#/definitions/MentorProfile'
        - type: object
          properties:
            _links:
              type: object
  MentorProfileResourceList:
    type: object
    properties:
      mentorProfileResourceList:
        type: array
        items:
          $ref: '#/definitions/MentorProfileResource'
  EmbeddedMentorProfileResourceList:
    type: object
    properties:
      _embedded:
        $ref: '#/definitions/MentorProfileResourceList'
      _links:
        type: object



