spring:
  datasource:
    url: jdbc:h2:mem:inno-edu-db
  jpa:
    hibernate:
      ddl-auto: false
  h2:
    console:
      enabled: true

flyway:
  cleanOnValidationError: true
  placeholders:
    map: lower

application:
  security:
    unsecured:
      - method: GET
        path: /**
      - method: POST
        path: /api/**
      - method: PUT
        path: /api/**
      - method: DELETE
        path: /api/**
